global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.2.3:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.2.4:8080"]

  # - job_name: "external-resources"
  #   static_configs:
  #     - targets: ["external.server1.com:9090", "external.server2.com:9090"]
