global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.2.3:9100"]
    metric_relabel_configs:
      # Add the server label dynamically
      - source_labels: [host]
        regex: "server2"
        target_label: server
        replacement: "server2"
      - source_labels: [host]
        regex: "server4"
        target_label: server
        replacement: "server4"

      # Relabel user ID to username dynamically
      - source_labels: [user]
        regex: "1014"
        target_label: username
        replacement: "breg"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.2.4:8080"]