{
 "title": "HostingServers",
 "description": "HostingServers",
 "tags": [
  "Servers",
  "Linux",
  "Cpanel"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage server4",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_usage_percent{host=\"server4\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage server2",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_usage_percent{host=\"server2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage server1",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_usage_percent{host=\"server1\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory-to-CPU Usage Ratio",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memory_usage_percent{host=\"server1\"} / cpu_usage_percent{host=\"server1\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk S4",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "disk_usage_percent{host=\"server4\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk S2",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "disk_usage_percent{host=\"server2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk S1",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "disk_usage_percent{host=\"server1\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory-to-CPU Usage Ratio",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 17, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memory_usage_percent{host=\"server2\"} / cpu_usage_percent{host=\"server2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mem S4",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memory_usage_percent{host=\"server4\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mem S2",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memory_usage_percent{host=\"server2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mem S1",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memory_usage_percent{host=\"server1\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory-to-CPU Usage Ratio",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 17, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memory_usage_percent{host=\"server4\"} / cpu_usage_percent{host=\"server4\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPUs All Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu Usage",
     "type": "timeseries",
     "description": "Server2 and $",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_percent{host=\"server2\"} /100",
       "legendFormat": "{{host}}"
      },
      {
       "expr": "cpu_usage_percent{host=\"server4\"} /100",
       "legendFormat": "{{host}}"
      },
      {
       "expr": "cpu_usage_percent{host=\"server1\"} /100",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Max Cpu Usage",
     "type": "timeseries",
     "description": "Server2 and $",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(cloudlinux_cpu_max /100) by (host)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG Cpu Usage",
     "type": "timeseries",
     "description": "Server2 and $",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(cloudlinux_cpu_avg) by (host) /100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory All Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(memory_usage_percent{host=\"server1\"})",
       "legendFormat": "Server1"
      },
      {
       "expr": "avg(memory_usage_percent{host=\"server2\"})",
       "legendFormat": "Server2"
      },
      {
       "expr": "avg(memory_usage_percent{host=\"server4\"})",
       "legendFormat": "Server4"
      }
     ]
    },
    {
     "title": "MAX Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "max(cloudlinux_pmem_max / 1024 / 1024 / 1024) by (host)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "VirtualMemory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "VirtualMemory Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 312 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(cloudlinux_vmem_avg /1024 /1024 /1024) by (host)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VirtualMemory Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 312 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum((cloudlinux_pmem_avg + cloudlinux_vmem_avg)/1024 /1024 /1024) by (host)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Server1 Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by All Users S1",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(cloudlinux_cpu_avg{host=\"server1\"} / cloudlinux_cpu_limit{host=\"server1\"}) * 100",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Memory Usage by All Users S1",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 144 },
     "targets": [
      {
       "expr": "(cloudlinux_pmem_avg{host=\"server1\"} / cloudlinux_pmem_max{host=\"server1\"} * 100)",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "CPU&MEM Usage by All Users S1",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n  (cloudlinux_cpu_avg{host=\"server1\"} / cloudlinux_cpu_limit{host=\"server1\"}) * 100\n) or (\n  (cloudlinux_pmem_avg{host=\"server1\"} / cloudlinux_pmem_max{host=\"server1\"}) * 100\n)",
       "legendFormat": "{{username}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server2 Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by All Users S2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(cloudlinux_cpu_avg{host=\"server2\"} / cloudlinux_cpu_limit{host=\"server2\"}) * 100",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Memory Usage by All Users S2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 145 },
     "targets": [
      {
       "expr": "(cloudlinux_pmem_avg{host=\"server2\"} / cloudlinux_pmem_max{host=\"server2\"} * 100)",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "CPU&MEM Usage by All Users S2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n  (cloudlinux_cpu_avg{host=\"server2\"} / cloudlinux_cpu_limit{host=\"server2\"}) * 100\n) or (\n  (cloudlinux_pmem_avg{host=\"server2\"} / cloudlinux_pmem_max{host=\"server2\"}) * 100\n)",
       "legendFormat": "{{username}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server4 Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by All Users S4",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 463 },
     "targets": [
      {
       "expr": "(cloudlinux_cpu_avg{host=\"server4\"} / cloudlinux_cpu_limit{host=\"server4\"}) * 100",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Memory Usage by All Users S4",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 463 },
     "targets": [
      {
       "expr": "(cloudlinux_pmem_avg{host=\"server4\"} / cloudlinux_pmem_max{host=\"server4\"} * 100)",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "CPU&MEM Usage by All Users S4",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 475 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n  (cloudlinux_cpu_avg{host=\"server4\"} / cloudlinux_cpu_limit{host=\"server4\"}) * 100\n) or (\n  (cloudlinux_pmem_avg{host=\"server4\"} / cloudlinux_pmem_max{host=\"server4\"}) * 100\n)",
       "legendFormat": "{{username}}"
      }
     ]
    }
   ]
  }
 ]
}